# Copyright (c) 2018-2025 Zerocracy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the 'Software'), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  SuggestExtensions: false

Style/ClassAndModuleChildren:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
Style/CommandLiteral:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 300
Metrics/AbcSize:
  Max: 130
Metrics/BlockLength:
  Max: 350
Metrics/BlockNesting:
  Max: 4
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Layout/LineLength:
  Max: 120
Metrics/ParameterLists:
  Max: 10
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
