AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  SuggestExtensions: false

Style/ClassAndModuleChildren:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
Style/CommandLiteral:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 300
Metrics/AbcSize:
  Max: 130
Metrics/BlockLength:
  Max: 350
Metrics/BlockNesting:
  Max: 4
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Layout/LineLength:
  Max: 120
Metrics/ParameterLists:
  Max: 10
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
