# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  SuggestExtensions: false
plugins:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake
  - rubocop-elegant
Lint/NumberConversion:
  Enabled: false
Style/TopLevelMethodDefinition:
  Enabled: false
Lint/RescueException:
  Enabled: false
Minitest/MultipleAssertions:
  Enabled: false
Minitest/SkipWithoutReason:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
Metrics/AbcSize:
  Max: 130
Metrics/BlockLength:
  Max: 350
Metrics/BlockNesting:
  Max: 4
Elegant/GoodMethodName:
  AllowedNames:
    - add_cold
    - anon_ip
    - confirmed_user
    - default_env
    - delete_expired
    - delete_failed
    - delete_succeeded
    - job_link
    - next_of
    - parsed_amount
    - pay_hosting_bonuses
    - pay_taxes
    - register_referral
    - remove_banned
    - remove_old
    - repeat_succeeded
    - replace_id
    - safe_md
    - send_payouts_api
    - system_consumed
    - t_log
    - t_pgsql
    - test_200_user_pages
    - test_302_user_pages
    - title_md
    - user_log
    - wallet_exists?
Elegant/GoodVariableName:
  AllowedNames:
    - '@@t_pgsql'
    - '@t_log'
    - daily_limit
    - monthly_limit
    - weekly_limit
