architect:
  - yegor256
  - davvd
docker:
  image: yegor256/rultor-image:1.13.0
readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/zold/wts-config.yml
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
install: |-
  export PATH=$PATH:/usr/lib/postgresql/12/bin
  sudo apt-get -y update
  sudo apt-get -y install libpq-dev
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  sensitive:
    - config.yml
  script: |-
    bundle exec rake --quiet
    git remote add dokku dokku@dokku.zold.io:wts
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git fetch
    sed -i "s/0\.0\.0/${tag}/g" ./version.rb
    release=$(git rev-parse --short HEAD)
    sed -i "s/000000/${release}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    cp ../config.yml config.yml
    git add config.yml
    git commit -m 'config.yml'
    git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm -rf target/pgsql-config.yml
    bundle exec rake liquibase
    rm -rf config.yml
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 https://wts.zold.io > /dev/null
merge:
  script: |-
    bundle exec rake --quiet
