# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
architect:
  - yegor256
docker:
  image: yegor256/java
readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/zold/wts-config.yml
release:
  sensitive:
    - config.yml
  script: |-
    bundle exec rake
    rm -rf target
    cp ../config.yml config.yml
    bundle exec rake liquibase
    rm -rf config.yml
merge:
  script: |-
    bundle exec rake
