---
name: codecov
on:
  push:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-14
          sudo ln -s /usr/lib/postgresql/14/bin/initdb /bin/initdb
          sudo ln -s /usr/lib/postgresql/14/bin/postgres /bin/postgres
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle update
      - run: bundle exec rake
      - uses: codecov/codecov-action@v3
        with:
          file: coverage/.resultset.json
          fail_ci_if_error: true
